### ISSUE TITLE
已定义的实例如何清除？

### ISSUE THREAD

**Issue by ZHEXIY** [IceTiki/matrixDisplacementMethod#4]
感谢大佬！请问在同一代码文件中，如果已经定义完一系列Nodes和Elements并生成了Struction后，该如何将所有的Nodes，Elements和Struction清除呢？因为我希望通过迭代来实现结构的自动计算与优化。我是个python新手，可能问题比较基础，万望解答，感谢！

**Comment by IceTiki** [comment]
如果是想迭代优化，如果结构不变（节点和连杆的连接关系不变），你可以试着直接重新设数值。

简单粗暴的办法是干脆重建所有节点连杆，重新建一个结构。

**Comment by ZHEXIY** [comment]
您的邮件我已收到，我会尽快回复。杨哲晰。

**Comment by IceTiki** [comment]
两个结构如果没有共用同样的节点/元素是相互独立的。其实一般不需要手动删除旧的（不用的变量python会自动帮你垃圾回收）

**Comment by IceTiki** [comment]
如果迭代优化如果不改变结构的连接关系，只改变数值。可以用set_properties函数

**Comment by ZHEXIY** [comment]
> 两个结构如果没有共用同样的节点/元素是相互独立的。其实一般不需要手动删除旧的（不用的变量python会自动帮你垃圾回收）

非常感谢！
